name: 'ServiceNow DevOps Sonar Scan Results'
description: 'Send Sonar Information to ServiceNow Devops'
inputs:
  instance-url: 
    description: 'ServiceNow Instance URL'
    required: true
  devops-integration-user-name:
    description: 'Devops Integration User Name'
    required: false
  devops-integration-user-password:
    description: 'Devops Integration User Password'
    required: false
  devops-security-token:
    description: 'Devops Security Token'
    required: false
  tool-id:
    description: 'Orchestration Tool Id'
    required: true
  context-github:
    description: 'Github Context'
    required: true
  job-name:
    description: 'Display Name of the Job'
    required: true
  sonar-host-url:
    description: 'Sonar Host URL'
    required: true
  sonar-project-key:
    description: 'Sonar Project Key'
    required: true
branding:
  icon: 'refresh-ccw'
  color: 'green'
runs: 
  using: 'node12'
  main: 'dist/index.js'
