name: workflowToken

on:
  workflow_dispatch:

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - name: Install dependencies
      run: npm ci

    - name: Compile
      run: npm run build
  sonarAction:
    needs: build
    runs-on: ubuntu-latest
    name: ServiceNow Devops Sonar

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: ServiceNow Devops Sonar
        uses: ServiceNow/servicenow-devops-sonar@1.39.0
        id: update
        with:
          devops-integration-token: ${{ secrets.SN_DEVOPS_INTEGRATION_TOKEN }}
          instance-url: ${{ secrets.SN_INSTANCE_URL }}
          tool-id: ${{ secrets.SN_ORCHESTRATION_TOOL_ID }}
          context-github: ${{ toJSON(github) }}
          job-name: 'Devops Sonar'
          sonar-host-url: ${{ secrets.SONAR_URL }}
          sonar-project-key: ${{ secrets.SONAR_PROJECT_KEY }}

